name: Discord Webhook Action

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Basic Content Test
        uses: ./
        with:
          webhook-url: https://discord.com/api/webhooks/1289489051166048297/tf92BzPVbTjURawWB4JA6wRTmZ-Elsql2xC3nspaCk-50_JgjrYanNgGqAAnvnskYSLq
          content: test
            
