name: Discord Webhook Action

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: https://discord.com/api/webhooks/1289489051166048297/tf92BzPVbTjURawWB4JA6wRTmZ-Elsql2xC3nspaCk-50_JgjrYanNgGqAAnvnskYSLq
          raw-data: hi.json
            
